---
- name: Tap Homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/binary
    - homebrew/completions
    - homebrew/dupes
    - homebrew/versions

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - awscli
    - bash
    - bash-completion
    - cask
    - caskroom/cask/brew-cask
    - cloc
    - coreutils
    - curl
    - direnv
    - flyway
    - fswatch
    - gist
    - git
    - gnu-sed
    - heroku
    - leiningen
    - maven
    - mercurial
    - node
    - openssl
    - pkg-config
    - packer
    - postgresql
    - protobuf
    - pv
    - sbt
    - scala
    - ssh-copy-id
    - subversion
    - terraform
    - the_silver_searcher
    - tig
    - tmux
    - tree
    - typesafe-activator
    - unrar
    - vagrant-completion
    - vcprompt
    - vim
    - watch
    - weechat
    - wget
    - wireshark
    - wrk
    - docker-completion
    - maven-completion
    - packer-completion
    - vagrant-completion

- name: Install aspell with Homebrew
  homebrew: name=aspell state=latest install_options=all

- name: Install emacs with Homebrew
  homebrew: name=emacs state=linked install_options=cocoa

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

- name: Install libraries with Homebrew cask
  homebrew_cask: name={{ item }}
  with_items:
   - consul
   - vagrant
   - java
