- hosts: targets
  gather_facts: False
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/homebrew.yml
    - include: tasks/go.yml
    - include: tasks/npm.yml
    - include: tasks/vim.yml
    - include: tasks/cheatsheets.yml

